### ISSUE TITLE
Windows code not robust

### ISSUE THREAD

**Issue by retep998** [alexcrichton/wait-timeout#1]
It currently checks the exit code `STILL_ACTIVE` to determine whether the process has terminated or not. This is prone to incorrect behavior if a process legitimately returns an exit code of 259. Instead this should depend on the return value from `WaitForSingleObject`. If that returns `WAIT_OBJECT_0` then the process has terminated, if it returns `WAIT_TIMEOUT` then it timed out.

**Comment by alexcrichton** [comment]
Thanks for the sharp eye! Fixed in https://github.com/alexcrichton/wait-timeout/commit/cc91c7a16f43a0415f579afb5ce94e2714e87b0d
