### ISSUE TITLE
Use `pdfork` support where supported

### ISSUE THREAD

**Issue by mathstuf** [alexcrichton/wait-timeout#13]
Would it be possible to use `procdesc` to support #4? This would drop the need to register a signal handler.

FreeBSD manpages:

  - [`pdwait4`](https://www.freebsd.org/cgi/man.cgi?query=pdwait4&sektion=2&apropos=0&manpath=FreeBSD+11.0-RELEASE+and+Ports)
  - [`procdesc`](https://www.freebsd.org/cgi/man.cgi?query=procdesc&sektion=4&apropos=0&manpath=FreeBSD+11.0-RELEASE+and+Ports)

**Comment by mathstuf** [comment]
Heh, `pdwait4` is not implemented yet it seems. I suppose since we need `poll` anyways, `wait4` could be used instead with the pid directly.

**Comment by alexcrichton** [comment]
Yeah unless there's a concrete technical reason that's compelling to do this, I'd probably avoid it.

**Comment by mathstuf** [comment]
Well, it'd be with the goal of getting #4 supportable on at least a few platforms. I don't know what to do about Linux; it seems that there are lots wanting a `pdfork` or `forkfd` syscall, but I haven't seen any progress anywhere on actually making it happen.

**Comment by alexcrichton** [comment]
Something like #4 is probably best done with tokio-process, not w/ just this crate in general

**Comment by mathstuf** [comment]
Ok, that sounds reasonable. Closing this.
