### ISSUE TITLE
CPU time timeout?

### ISSUE THREAD

**Issue by AdrienChampion** [alexcrichton/wait-timeout#16]
Naive question: is there any hope to have a `wait_cpu_timeout` in the future ?

**Comment by alexcrichton** [comment]
Perhaps! I don't know of the native apis to do this, but if they exist they can be bound for sure

**Comment by AdrienChampion** [comment]
I'll try to take a look soon-ish and let you know / submit a PR.

**Comment by AdrienChampion** [comment]
I thought I had a use-case for this but it turns out I don't! I'm not convinced this would be useful for anyone, so let me go ahead and close the issue.
