### ISSUE TITLE
Contructible ExitStatus

### ISSUE THREAD

**Issue by flg** [alexcrichton/wait-timeout#17]
It would be nice to be able to construct ExitStatus (fails due to private fields for now, as well as std::process::ExitStatus).

The use case is generic code where the wait timeout is configurable. When the desired timeout is infinite, one has to fallback to calling std::process::Child::wait. For genericity it looks natural to want to create a wait-timeout::ExitStatus out of the std::process::ExitStatus.

Example:
```
if timeout.is_none() {
    status_code_res = match child.wait() {
        Ok(x) => Ok(Some(ExitStatus(x))),
        Err(x) => Err(x),
    };
} else {
    status_code_res = child.wait_timeout(timeout.unwrap());
}
```

Another solution to address this is to accept an infinite value as input parameter (Option<Duration> seems appropriate).

**Comment by alexcrichton** [comment]
Thanks for the report! This is a pretty old crate at this point, and nowadays we can just use the standard library `ExitStatus` as-is!
