### ISSUE TITLE
Is it feasible to make this work with wasm32?

### ISSUE THREAD

**Issue by svenstaro** [alexcrichton/wait-timeout#18]
Basically, as the title says, I'd like to run this on wasm32 or at least emscripten. Do you think that's feasible somehow?

**Comment by alexcrichton** [comment]
A good question! Unfortunately though not at this time :(

The `Command` type in the standard library, which this builds on, doesn't work on wasm32. It's possible, however, to get this *building* on wasm32 (and just panic/return errors). Would that work for your use case?

**Comment by svenstaro** [comment]
I'm not sure. My particular use case is that I want to use proptest with wasm and that uses rusty-fork and that uses wait-timeout.

**Comment by alexcrichton** [comment]
Ah ok, in that case I think that the goal here needs to be achieved with a different implementation strategy on wasm because wasm can't fork

**Comment by lastmjs** [comment]
Any suggestions on getting around this? I am trying to get proptest to compile for a Wasm environment (not the browser, wasmtime for use on the [Internet Computer](https://dfinity.org/)).
